[package]
name = "zkguard"
type = "bin"
authors = ["Ziemann"]


[dependencies]
keccak256 = { git = "https://github.com/noir-lang/keccak256", tag = "v0.1.0" }
ecrecover = { git = "https://github.com/colinnielsen/ecrecover-noir", tag = "v1.0.0" }
