[package]
name = "zkguard-methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { version = "3.0.3", features = ["unstable"] }
risc0-build-ethereum = "3.0.1"

[package.metadata.risc0]
methods = ["guest"]